id: P005519
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-17 11:56:05.312647
source_metadata:
  id: bdr:W1KG24612
  title: བསམ་གཟུགས་ཀྱི་མཐའ་དཔྱོད་འབྲིང་པོ།
  author: ''
  volumes:
    89f76bd35eb544fcb7801f34d8a906ea:
      image_group_id: I1KG24625
      title: ''
      volume_number: 1
      total_pages: 310
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
