id: P005519
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG24612
  title: བསམ་གཟུགས་ཀྱི་མཐའ་དཔྱོད་འབྲིང་པོ།
  author: ''
  volumes:
    89f76bd35eb544fcb7801f34d8a906ea:
      image_group_id: I1KG24625
      title: ''
      volume_number: 1
      total_pages: 310
      base_file: v001.txt
