id: I5C4B29D2
legacy_id: P005519
ocr_import_info:
  bdrc_scan_id: W1KG24612
  source: bdrc
  ocr_info:
    timestamp: '2020-03-25T12:26:45'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T13:49:09.586220+00:00'
last_modified: 2022-08-31 21:49:34.405216
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG24612
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG24612
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: བསམ་གཟུགས་ཀྱི་མཐའ་དཔྱོད་འབྲིང་པོ།
  author: བསེ་ཚང ༠༡་ངག་དབང་བཀྲ་ཤིས།
statistics:
  ocr_word_mean_confidence_index: 0.7145131777837334
  ocr_word_median_confidence_index: 0.9599999785423279
quality: null
bases:
  I1KG24625:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG24625
      total_pages: 310
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG24625.txt
    statistics:
      ocr_word_median_confidence_index: 0.9599999785423279
      ocr_word_mean_confidence_index: 0.7145131777837334
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
